name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  pull-requests: write
  
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: adipurnamk/my_nginx_app:0.0.1
  plan:
    runs-on: ubuntu-latest
    name: Apply Terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply backennd
        uses: dflook/terraform-apply@v1
        continue-on-error: true
        with:
          path: infrastructure/backend

      - name: terraform apply backennd
        uses: dflook/terraform-apply@v1
        continue-on-error: true
        id: infrastructure
        with:
          path: infrastructure
          
      - name: Retry failed apply
        uses: dflook/terraform-apply@v1
        if: ${{ steps.infrastructure.outputs.failure-reason == 'apply-failed' }}
        with:
          path: infrastructure
          auto_approve: true
